version: '3'
services:
    yarn:
        image: node:8.11
        env_file: .env
        network_mode: host
        entrypoint: yarn
        ports:
            - "$PORT:$PORT"
        working_dir: /app
        volumes:
            - .:/app
